name: Deploy to staging url
'on':
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEAGUE_BEEGAME_GG }}'
          channelId: staging
          projectId: league-beegame-gg
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
